import Head from 'next/head'
import styles from '../../styles/Layout.module.scss'

export default function Layout({children, title}){
    return(
        <>
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
            <div className={styles.mainBorder}></div>
            <div className={styles.pageContent}>
                {children}
            </div>
        </div>
        </>
    )
}