import Head from 'next/head'
import { Flex, Box } from 'rebass'
import styles from '../../styles/Layout.module.scss'

export default function Layout({children, title}){
    return(
        <Box height="100%" >
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* <div className={styles.mainBorder}></div> */}
            {children}
            
        </Box>
    )
}