import Head from 'next/head'
import { Flex, Box } from 'rebass'
import styles from '../../styles/Layout.module.scss'
import Nav from './nav'

export default function Layout({children, title}){
    return(
        <Box height="100%" >
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://use.typekit.net/gbc4ufr.css" />
            </Head>
            {/* <div className={styles.mainBorder}></div> */}
            <Nav />
            {children}
            
        </Box>
    )
}